### ISSUE TITLE
POLICER:SAI_POLICER_ATTR_PIR should not be needed for SR_TCM

### ISSUE THREAD

**Issue by lguohan** [Azure/sonic-sairedis#136]
See below error in policer validation when swssconfig tries to push trap group configurations. To workaround it, I had to add PIR attribute to copp.json. Since the meter type is SAI_POLICER_MODE_SR_TCM, I am not sure why PIR is expected as mandatory. Appreciate if this can be clarified.

Dec 14 20:37:12 switch3 WARNING orchagent: :- processCoppRule: Creating policer for existing Trap group:f000000000003 (name:default).
Dec 14 20:37:12 switch3 ERR orchagent: :- meta_generic_validation_create: POLICER:SAI_POLICER_ATTR_PIR:UINT64 attribute is conditional and is mandatory but not passed in attr list
Dec 14 20:37:12 switch3 ERR orchagent: :- createPolicer: Failed to create policer for existing trap_group_name:f000000000003, name:default, error:-14
Dec 14 20:37:12 switch3 ERR orchagent: :- doTask: Processing copp task item failed, exiting.

**Comment by kcudnik** [comment]
from 9.4.0:
 /** Peak information rate BPS/PPS based on
     * SAI_POLICER_ATTR_METER_TYPE [uint64_t]
     * Mandatory only for SAI_POLICER_MODE_Tr_TCM */
    SAI_POLICER_ATTR_PIR = 0x00000006,

and from sairedis:
 .conditions             = { COND_ENUM ( SAI_POLICER_ATTR_METER_TYPE, SAI_POLICER_MODE_Tr_TCM ) },

so this seems to be correct, if error occures on SAI_POLICER_MODE_SR_TCM then maybe there is enum number missmatch on those values, recompile against the same sai headers ? or there maybe a bug in meta logic

**Comment by kcudnik** [comment]
closing this since there is no more intres in this issu for a long time
