### ISSUE TITLE
Operational status is nil after system start up for ports with linkDown status 

### ISSUE THREAD

**Issue by NStetskovych** [Azure/sonic-sairedis#183]
This is because orgagent haven`t start to get on_port_state_change notification.
After triggering link status to up/down operational status become correct.

show version 

SONiC Software Version: SONiC.HEAD.149-8af03fd
Distribution: Debian 8.8
Kernel: 3.16.0-4-amd64
Build commit: 8af03fd
Build date: Tue May 16 04:41:05 UTC 2017
Built by: johnar@jenkins-worker-1

Docker images:
REPOSITORY                TAG                 IMAGE ID            SIZE
docker-orchagent-cavm     latest              6068b8895ea5        257.7 MB
docker-syncd-cavm         latest              8ddae1f89263        297.9 MB
docker-dhcp-relay         latest              021514bcc010        252.8 MB
docker-database           latest              7872aec5900d        220.8 MB
docker-snmp-sv2           latest              498cd73cdf7c        290.5 MB
docker-teamd              latest              da176f334b6b        254.7 MB
docker-platform-monitor   latest              39e4618ae9b1        269.9 MB
docker-lldp-sv2           latest              ca07da5c55f4        256.3 MB
docker-fpm-quagga         latest              f7c6d0818c8f        261.2 MB

**Comment by kcudnik** [comment]
What do you mean "nil" ? Where from you get this value ? What is actual scenario you are testing, can you provide steps ?

**Comment by NStetskovych** [comment]
Steps:
Just load the image and start system
root@sonic:/home/admin# redis-cli 
127.0.0.1:6379> hget PORT_TABLE:Ethernet4 oper_status
"up"
127.0.0.1:6379> hget PORT_TABLE:Ethernet72 oper_status
(nil)
127.0.0.1:6379> 
Operation status not set for ports with link down status.

**Comment by lguohan** [comment]
can you check the sairedis dump to see if your sai driver send any port status change notification? If not, then the oper_status is nil. 

If we do not get any notification from sai, can we assume the open status is in down state?

http://lists.opencompute.org/pipermail/opencompute-sai/2017-May/000223.html

**Comment by NStetskovych** [comment]
After switch initialization sai send  port status change notification but there is no one that is listen to.
Thus operational status become correct if only port link status changes.
Not sure about some default operational status to solve this issue.
I think similar behavior should be on other platform. 
root@sonic:/home/admin# redis-cli 
127.0.0.1:6379> hget PORT_TABLE:Ethernet72 oper_status
(nil)
127.0.0.1:6379> hget PORT_TABLE:Ethernet76 oper_status
(nil)
127.0.0.1:6379> hget PORT_TABLE:Ethernet104 oper_status
"up"
127.0.0.1:6379> exit
root@sonic:/home/admin#  cat /var/log/syslog | grep "SAI: Link down"
May 22 12:35:13.0 sonic INFO supervisord: syncd 12:35:13 SAI DEBUG: xpSaiSwitchLinkDownEventNotification(): SAI: Link down interrupt received on port: 0, devId: 0
May 22 12:35:13.0 sonic INFO supervisord: syncd 12:35:13 SAI DEBUG: xpSaiSwitchLinkDownEventNotification(): SAI: Link down interrupt received on port: 4, devId: 0
May 22 12:35:13.0 sonic INFO supervisord: syncd 12:35:13 SAI DEBUG: xpSaiSwitchLinkDownEventNotification(): SAI: Link down interrupt received on port: 8, devId: 0
May 22 12:35:13.0 sonic INFO supervisord: syncd 12:35:13 SAI DEBUG: xpSaiSwitchLinkDownEventNotification(): SAI: Link down interrupt received on port: 12, devId: 0
May 22 12:35:13.0 sonic INFO supervisord: syncd 12:35:13 SAI DEBUG: xpSaiSwitchLinkDownEventNotification(): SAI: Link down interrupt received on port: 16, devId: 0
May 22 12:35:13.0 sonic INFO sup...............
root@sonic:/home/admin# date
Mon May 22 12:38:08 UTC 2017
root@sonic:/home/admin# cat /var/log/syslog | grep "**Get port state change notification**"
May 22 12:35:23.0 sonic NOTICE orchagent: :- on_port_state_change: Get port state change notification id:100000000001a status:1
root@sonic:/home/admin#  cat /var/log/syslog | grep "**Set operation status**"
May 22 12:35:23.0 sonic NOTICE orchagent: :- setHostIntfsOperStatus: Set operation status UP to host interface Ethernet104

**Comment by marian-pritsak** [comment]
@lguohan, as I understand, port operational status in SONiC is updated via notifications. And if there was no change since boot (port never was in up state), Record in Redis DB will have no info (nil).

So the question is, should orchagent initialize oper_status field with DOWN at beginning or shuold SAI implementation send first notification that port is DOWN after it was created?

Currently portstat assumes that if record in DB is nil, then state is DOWN

**Comment by kcudnik** [comment]
can you do in redis-cli> keys PORT_TABLE:Ethe*
and see what ports are available ?

**Comment by NStetskovych** [comment]
root@sonic:/home/admin# redis-cli 
127.0.0.1:6379> keys PORT_TABLE:Ethe*
 1) "PORT_TABLE:Ethernet28"
 2) "PORT_TABLE:Ethernet64"
 3) "PORT_TABLE:Ethernet96"
 4) "PORT_TABLE:Ethernet60"
 5) "PORT_TABLE:Ethernet52"
 6) "PORT_TABLE:Ethernet68"
 7) "PORT_TABLE:Ethernet16"
 8) "PORT_TABLE:Ethernet104"
 9) "PORT_TABLE:Ethernet84"
10) "PORT_TABLE:Ethernet40"
11) "PORT_TABLE:Ethernet44"
12) "PORT_TABLE:Ethernet112"
13) "PORT_TABLE:Ethernet20"
14) "PORT_TABLE:Ethernet76"
15) "PORT_TABLE:Ethernet88"
16) "PORT_TABLE:Ethernet24"
17) "PORT_TABLE:Ethernet124"
18) "PORT_TABLE:Ethernet4"
19) "PORT_TABLE:Ethernet36"
20) "PORT_TABLE:Ethernet0"
21) "PORT_TABLE:Ethernet108"
22) "PORT_TABLE:Ethernet92"
23) "PORT_TABLE:Ethernet116"
24) "PORT_TABLE:Ethernet8"
25) "PORT_TABLE:Ethernet72"
26) "PORT_TABLE:Ethernet100"
27) "PORT_TABLE:Ethernet12"
28) "PORT_TABLE:Ethernet56"
29) "PORT_TABLE:Ethernet120"
30) "PORT_TABLE:Ethernet80"
31) "PORT_TABLE:Ethernet48"
32) "PORT_TABLE:Ethernet32"

**Comment by lguohan** [comment]
@marian-pritsak, I share the same understanding with you. If the behavior you describe is the same for all platforms, (do not send notification when the port never up), I think the orchagent can initiate the port status to be down.

Meanwhile, @NStetskovych, can you confirm your platform has the same behavior as marian describes.

**Comment by NStetskovych** [comment]
Yes, it the same.
 I just try to send for test ( in my previous log).
@marian-pritsak describe it perfectly.

**Comment by lguohan** [comment]
@stcheng , can you set the port oper status to down as the default value in port orchagent?

**Comment by stcheng** [comment]
https://github.com/Azure/sonic-swss/pull/224
