### ISSUE TITLE
[SAI 1.0] Failed to set sairedis recording output dir

### ISSUE THREAD

**Issue by stcheng** [Azure/sonic-sairedis#215]
The function is called to set the folder to /var/log/swss. However, the recording file is still under /.

**Comment by kcudnik** [comment]
Probably when you set new output dir you need to restart recording or log rotate since new directory will take effect after those actions. We can discuss whether change log directory should automatically log rotate

**Comment by kcudnik** [comment]
I added fix in swss https://github.com/Azure/sonic-swss/pull/300

**Comment by kcudnik** [comment]
I also added https://github.com/Azure/sonic-sairedis/pull/216 so this or previousPR will fix the issue

**Comment by kcudnik** [comment]
Closing since resolved in other pull requests
