### ISSUE TITLE
SAI API failure feedback need to be done, we can not just crash swss if SAI API fails.

### ISSUE THREAD

**Issue by lguohan** [Azure/sonic-sairedis#239]

**Comment by kcudnik** [comment]
For all apis this will be design change

**Comment by sunnogo** [comment]
+1，in all platform, not just Mellanox.

**Comment by jipanyang** [comment]
+2   

<1> The sai_redis create/remove/set call should get feedback from syncd/libsai/asic. 

<2> In stead of crashing syncd with SWSS_LOG_THROW(),  error feedback should be passed up to orchagent whenever possible.   Same for sai_redis_generic_create/get in orchagent.

**Comment by kcudnik** [comment]
obsoleted by sync mode
