### ISSUE TITLE
Abnormal syncd termination

### ISSUE THREAD

**Issue by nikos-li** [Azure/sonic-sairedis#259]
Nov 16 23:49:36.819308 lca1-tx1-asw04 INFO supervisord: syncd terminate called without an active exception#015
Nov 16 23:49:36.825152 lca1-tx1-asw04 NOTICE dsserve: child /usr/bin/syncd exited status: 134
Nov 16 23:49:36.825474 lca1-tx1-asw04 INFO supervisord: syncd [5] child /usr/bin/syncd exited status: 134
Nov 16 23:49:43.781123 lca1-tx1-asw04 INFO supervisord 2017-11-16 23:49:36,825 INFO exited: syncd (exit status 3; not expected)
Nov 16 23:49:43.781123 lca1-tx1-asw04 INFO supervisord 2017-11-16 23:49:39,998 INFO reaped unknown pid 52

**Comment by stcheng** [comment]
this log is a truncated one which doesn't provide useful information. could you provide the full context about this crash?

**Comment by kcudnik** [comment]
Is there a coredump maybe ?

**Comment by lguohan** [comment]
need more information.
