### ISSUE TITLE
vs error at the startup time

### ISSUE THREAD

**Issue by lguohan** [Azure/sonic-sairedis#270]
Dec 19 02:13:53.296659 bfa8f5cc60f2 ERR syncd: :- veth2tap_fun: failed to write to tap device 63
Dec 19 02:13:53.552463 bfa8f5cc60f2 ERR syncd: :- veth2tap_fun: failed to write to tap device 67
Dec 19 02:13:54.064588 bfa8f5cc60f2 ERR syncd: :- veth2tap_fun: failed to write to tap device 61
Dec 19 02:13:54.576561 bfa8f5cc60f2 ERR syncd: :- veth2tap_fun: failed to write to tap device 51
Dec 19 02:13:54.576630 bfa8f5cc60f2 ERR syncd: :- veth2tap_fun: failed to write to tap device 65
Dec 19 02:13:54.832563 bfa8f5cc60f2 ERR syncd: :- veth2tap_fun: failed to write to tap device 69
Dec 19 02:13:55.088500 bfa8f5cc60f2 ERR syncd: :- veth2tap_fun: failed to write to tap device 59
Dec 19 02:13:55.600660 bfa8f5cc60f2 ERR syncd: :- veth2tap_fun: failed to write to tap device 55
Dec 19 02:13:56.113016 bfa8f5cc60f2 ERR syncd: :- veth2tap_fun: failed to write to tap device 53
Dec 19 02:13:56.368590 bfa8f5cc60f2 ERR syncd: :- veth2tap_fun: failed to write to tap device 49
Dec 19 02:13:56.368636 bfa8f5cc60f2 ERR syncd: :- veth2tap_fun: failed to write to tap device 57
Dec 19 02:13:56.368710 bfa8f5cc60f2 ERR syncd: :- veth2tap_fun: failed to write to tap device 75
Dec 19 02:13:56.624558 bfa8f5cc60f2 ERR syncd: :- veth2tap_fun: failed to write to tap device 79
Dec 19 02:13:56.624768 bfa8f5cc60f2 ERR syncd: :- veth2tap_fun: failed to write to tap device 71
Dec 19 02:13:57.136521 bfa8f5cc60f2 ERR syncd: :- veth2tap_fun: failed to write to tap device 105
Dec 19 02:13:57.136628 bfa8f5cc60f2 ERR syncd: :- veth2tap_fun: failed to write to tap device 73
Dec 19 02:13:57.392596 bfa8f5cc60f2 ERR syncd: :- veth2tap_fun: failed to write to tap device 103
Dec 19 02:13:57.648536 bfa8f5cc60f2 ERR syncd: :- veth2tap_fun: failed to write to tap device 85
Dec 19 02:13:57.648631 bfa8f5cc60f2 ERR syncd: :- veth2tap_fun: failed to write to tap device 81
Dec 19 02:13:57.904603 bfa8f5cc60f2 ERR syncd: :- veth2tap_fun: failed to write to tap device 83
Dec 19 02:13:57.904654 bfa8f5cc60f2 ERR syncd: :- veth2tap_fun: failed to write to tap device 77
Dec 19 02:13:58.160618 bfa8f5cc60f2 ERR syncd: :- veth2tap_fun: failed to write to tap device 101
Dec 19 02:13:58.416550 bfa8f5cc60f2 ERR syncd: :- veth2tap_fun: failed to write to tap device 87
Dec 19 02:13:58.416590 bfa8f5cc60f2 ERR syncd: :- veth2tap_fun: failed to write to tap device 109
Dec 19 02:13:58.672597 bfa8f5cc60f2 ERR syncd: :- veth2tap_fun: failed to write to tap device 95
Dec 19 02:13:58.928572 bfa8f5cc60f2 ERR syncd: :- veth2tap_fun: failed to write to tap device 93
Dec 19 02:13:59.184476 bfa8f5cc60f2 ERR syncd: :- veth2tap_fun: failed to write to tap device 91
Dec 19 02:13:59.184501 bfa8f5cc60f2 ERR syncd: :- veth2tap_fun: failed to write to tap device 107
Dec 19 02:13:59.440678 bfa8f5cc60f2 ERR syncd: :- veth2tap_fun: failed to write to tap device 99
Dec 19 02:13:59.696506 bfa8f5cc60f2 ERR syncd: :- veth2tap_fun: failed to write to tap device 97
Dec 19 02:13:59.952584 bfa8f5cc60f2 ERR syncd: :- veth2tap_fun: failed to write to tap device 111
Dec 19 02:13:59.952609 bfa8f5cc60f2 ERR syncd: :- veth2tap_fun: failed to write to tap device 89

**Comment by kcudnik** [comment]
was tap device created succesfully ? can you paste entire log ? what happened in the mean time ? did any of tap devices was removed/shutdown ?

**Comment by lguohan** [comment]
[syslog.gz](https://github.com/Azure/sonic-sairedis/files/1574746/syslog.gz)

I attached the entire log. For the log all of them are created successfully. I can see them in the vs container as well. I am using the sairedis v1.2 for this test.

**Comment by lguohan** [comment]
I printed the errno, 5? 

EIO    A low-level I/O error occurred while modifying the inode.


```
Dec 20 09:25:52.272615 3ec90020b80d ERR syncd: :- veth2tap_fun: failed to write to tap device 69, errno 5
Dec 20 09:25:52.784521 3ec90020b80d ERR syncd: :- veth2tap_fun: failed to write to tap device 67, errno 5
Dec 20 09:25:52.784575 3ec90020b80d ERR syncd: :- veth2tap_fun: failed to write to tap device 53, errno 5
Dec 20 09:25:52.784588 3ec90020b80d ERR syncd: :- veth2tap_fun: failed to write to tap device 71, errno 5
Dec 20 09:25:53.040575 3ec90020b80d ERR syncd: :- veth2tap_fun: failed to write to tap device 75, errno 5
Dec 20 09:25:53.296622 3ec90020b80d ERR syncd: :- veth2tap_fun: failed to write to tap device 55, errno 5
Dec 20 09:25:53.296679 3ec90020b80d ERR syncd: :- veth2tap_fun: failed to write to tap device 65, errno 5
Dec 20 09:25:54.064529 3ec90020b80d ERR syncd: :- veth2tap_fun: failed to write to tap device 73, errno 5
Dec 20 09:25:54.064549 3ec90020b80d ERR syncd: :- veth2tap_fun: failed to write to tap device 63, errno 5
Dec 20 09:25:54.832591 3ec90020b80d ERR syncd: :- veth2tap_fun: failed to write to tap device 77, errno 5
Dec 20 09:25:54.832645 3ec90020b80d ERR syncd: :- veth2tap_fun: failed to write to tap device 85, errno 5
Dec 20 09:25:54.832797 3ec90020b80d ERR syncd: :- veth2tap_fun: failed to write to tap device 105, errno 5
Dec 20 09:25:55.088575 3ec90020b80d ERR syncd: :- veth2tap_fun: failed to write to tap device 59, errno 5
Dec 20 09:25:55.344501 3ec90020b80d ERR syncd: :- veth2tap_fun: failed to write to tap device 61, errno 5
Dec 20 09:25:55.344521 3ec90020b80d ERR syncd: :- veth2tap_fun: failed to write to tap device 79, errno 5
Dec 20 09:25:55.344536 3ec90020b80d ERR syncd: :- veth2tap_fun: failed to write to tap device 57, errno 5
Dec 20 09:25:55.344555 3ec90020b80d ERR syncd: :- veth2tap_fun: failed to write to tap device 83, errno 5
Dec 20 09:25:55.344771 3ec90020b80d ERR syncd: :- veth2tap_fun: failed to write to tap device 115, errno 5
Dec 20 09:25:55.600542 3ec90020b80d ERR syncd: :- veth2tap_fun: failed to write to tap device 87, errno 5
Dec 20 09:25:55.856592 3ec90020b80d ERR syncd: :- veth2tap_fun: failed to write to tap device 91, errno 5
Dec 20 09:25:56.116519 3ec90020b80d ERR syncd: :- veth2tap_fun: failed to write to tap device 89, errno 5
Dec 20 09:25:56.116550 3ec90020b80d ERR syncd: :- veth2tap_fun: failed to write to tap device 93, errno 5
Dec 20 09:25:56.116580 3ec90020b80d ERR syncd: :- veth2tap_fun: failed to write to tap device 81, errno 5
Dec 20 09:25:56.368538 3ec90020b80d ERR syncd: :- veth2tap_fun: failed to write to tap device 113, errno 5
Dec 20 09:25:56.624561 3ec90020b80d ERR syncd: :- veth2tap_fun: failed to write to tap device 111, errno 5
Dec 20 09:25:56.880546 3ec90020b80d ERR syncd: :- veth2tap_fun: failed to write to tap device 99, errno 5
Dec 20 09:25:56.880574 3ec90020b80d ERR syncd: :- veth2tap_fun: failed to write to tap device 107, errno 5
Dec 20 09:25:56.884541 3ec90020b80d ERR syncd: :- veth2tap_fun: failed to write to tap device 95, errno 5
Dec 20 09:25:57.136558 3ec90020b80d ERR syncd: :- veth2tap_fun: failed to write to tap device 109, errno 5
Dec 20 09:25:57.392536 3ec90020b80d ERR syncd: :- veth2tap_fun: failed to write to tap device 97, errno 5
Dec 20 09:25:58.160566 3ec90020b80d ERR syncd: :- veth2tap_fun: failed to write to tap device 101, errno 5
Dec 20 09:25:58.928563 3ec90020b80d ERR syncd: :- veth2tap_fun: failed to write to tap device 103, errno 5
```

**Comment by lguohan** [comment]
[syncd.strace.gz](https://github.com/Azure/sonic-sairedis/files/1575096/syncd.strace.gz)
[syslog.gz](https://github.com/Azure/sonic-sairedis/files/1575097/syslog.gz)

looking at the syncd strace, I feel EIO can be a temp error. probably, we should ignore the error and continue.

**Comment by lguohan** [comment]
https://mail.openvswitch.org/pipermail/ovs-dev/2016-June/316261.html

looks like when the tap device is not up, you will get this EIO. I wonder which kernel did you do the test?

**Comment by lguohan** [comment]
here is the kernel commit 

https://github.com/torvalds/linux/commit/1bd4978a88ac2589f3105f599b1d404a312fb7f6

**Comment by pavel-shirshov** [comment]
I don't see such code in 3.16.51
http://elixir.free-electrons.com/linux/v3.16.51/source/drivers/net/tun.c
Is debian added the change you mentioned into the debian kernel?

**Comment by lguohan** [comment]
this is about the virtual switch which is running on my dev box. since I am using ubuntu 16.04, it is using 4.11.0-1016-azure kernel. That is why I think I am seeing the problem.

**Comment by pavel-shirshov** [comment]
got it

**Comment by kcudnik** [comment]
@lguohan  I previously added this "ifup" mothod https://github.com/Azure/sonic-sairedis/blob/master/vslib/src/sai_vs_hostintf.cpp#L141 and it was executed after creating tap interface, but you mentioned to remove this so i did, that orchagent should bring those interfaces up anyway, but if thats the case then it seems like some packets already arrive when tap device is not up yet

**Comment by lguohan** [comment]
@kcudnik , sometimes we need to put admin down for the host interface (tap interface), and the peer might still send to this host interface and thus trigger such condition.

**Comment by kcudnik** [comment]
i will try to add listener for interface change for current netlink, and if some interface will go down i will check that and wont write packets to that interface

**Comment by kcudnik** [comment]
Resolved
