### ISSUE TITLE
Mac entries in ASIC_DB can't be flushed when receive SAI_FDB_EVENT_FLUSHED from SAI

### ISSUE THREAD

**Issue by keboliu** [Azure/sonic-sairedis#272]
in function _void redisPutFdbEntryToAsicView( _In_ const sai_fdb_event_notification_data_t *fdb)_ when it handles the _SAI_FDB_EVENT_FLUSHED_ event it expecting all the flushed entries will be carried as the _SAI_FDB_EVENT_AGED_  case.

```
if ((fdb->event_type == SAI_FDB_EVENT_AGED)||(fdb->event_type == SAI_FDB_EVENT_FLUSHED))
{
        if (fdb->event_type == SAI_FDB_EVENT_AGED)
        {
            SWSS_LOG_DEBUG("remove fdb entry %s for SAI_FDB_EVENT_AGED",key.c_str());
        }
        if (fdb->event_type == SAI_FDB_EVENT_FLUSHED)
        {
            SWSS_LOG_DEBUG("remove fdb entry %s for SAI_FDB_EVENT_FLUSHED",key.c_str());
        }
        g_redisClient->del(key);
        return;
 }
```

 But seems this is not the case.  I did some test on MLNX platform, in the mac entry flush case, SAI only send one '00:00:00:00:00:00' mac entry with the event.

_2018-01-01.09:41:55.073229|n|fdb_event|[{"fdb_entry":"{\"bridge_id\":\"oid:0x0\",\"bridge_type\":\"SAI_FDB_ENTRY_BRIDGE_TYPE_1Q\",\"mac\":\"00:00:00:00:00:00\",\"switch_id\":\"oid:0x21000000000000\",\"vlan\":\"0\"}","fdb_event":"SAI_FDB_EVENT_FLUSHED","list":[{"id":"SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID","value":"oid:0x0"},{"id":"SAI_FDB_ENTRY_ATTR_TYPE","value":"SAI_FDB_ENTRY_TYPE_DYNAMIC"},{"id":"SAI_FDB_ENTRY_ATTR_PACKET_ACTION","value":"SAI_PACKET_ACTION_FORWARD"}]}]|_

I am not sure the situation on other platforms?

**Comment by lguohan** [comment]
is this a mellanox sai issue as the mac address in the fdb notification is not valid?

**Comment by lguohan** [comment]
I also noticed that in some SAI, there will be no flush fdb notification when flush API is called, in this case, we need to manually remove all the fdb entries in the asic db. I think a proper solution is as follows:

1. call bridge port admin down
2. flush the fdb entries for this bridge port
3. bring up the bridge port

This procedure also ensure there will be no race conditions since when we try to delete fdb entry in the asic db, there is another fdb notification from the asic.

**Comment by keboliu** [comment]
the code in function "redisPutFdbEntryToAsicView" is taken an assumption that in fdb flush event all the flushed mac entries should be sent to syncd by SAI, the question is whether we should take this assumption? Is the SAI flush fdb event callback designed in this way?

**Comment by kcudnik** [comment]
when that functionality was implemente we were not using configuration where we used fdb entries a lot, and not this needs to be fixed
