### ISSUE TITLE
support get_port/queue/ingress_priority_group_stats in virtual switch

### ISSUE THREAD

**Issue by lguohan** [Azure/sonic-sairedis#310]
need to support 
get_queue_stats
get_ingress_priority_group_stats
get_port_stats

The virtual switch can return all zero for all counters.

We also need set_counter support to allow application to set those counters for swss integration test framework.

**Comment by kcudnik** [comment]
merged

**Comment by lguohan** [comment]
can we also do set counter for the swss integration test?
