### ISSUE TITLE
Warm reboot:  view comparison for LAG

### ISSUE THREAD

**Issue by jipanyang** [Azure/sonic-sairedis#354]
This is to record the open issue related to lag processing in current view comparison logic, for tracking purpose.

As commented in https://github.com/Azure/sonic-sairedis/pull/351,  the special comparison logic for LAG didn't take into account the case of lag member being removed/disabled temporarily before warm reboot.   Further fix is needed to handle that scenario.

**Comment by kcudnik** [comment]
sairedis part is done using SAI lag attribute
