### ISSUE TITLE
Is this expected for syncd to send shutdown request when a dynamic route is failed to be added due to table full? 

### ISSUE THREAD

**Issue by vsenchyshyn** [Azure/sonic-sairedis#432]
We've faced the situation when syncd sends shutdown notification (https://github.com/Azure/sonic-sairedis/blob/master/syncd/syncd.cpp#L2792) when a dynamic route is failed to be added (https://github.com/Azure/sonic-sairedis/blob/master/syncd/syncd.cpp#L2747) due to table full. 

At the same time in orchagent such a fail doesn't seem to be something critical as it doesn't raise any runtime error on route add fail: https://github.com/Azure/sonic-swss/blob/316ae6c0d2a47c95b3becb89497c42e46404b252/orchagent/routeorch.cpp#L809

So, is this situation with shutdown notification sent expected scenario or this is an issue?

**Comment by kcudnik** [comment]
in asynchronous mode this is expected as every api is assumed to success, OA will think it succeeded
