### ISSUE TITLE
service syncd stop broken on mlnx platform

### ISSUE THREAD

**Issue by lguohan** [Azure/sonic-sairedis#44]
root@str-msn2700-1:/# service syncd stop 
start-stop-daemon: option '--exec' requires an argument
Try 'start-stop-daemon --help' for more information.
root@str-msn2700-1:/#

**Comment by stcheng** [comment]
It solves the issue https://github.com/Azure/sonic-sairedis/issues/44

**Comment by stcheng** [comment]
resolved in (#46)
