### ISSUE TITLE
Warm-reboot: SET request on ACL Entry with wrong ACL Counter ID

### ISSUE THREAD

**Issue by anirudhnr** [Azure/sonic-sairedis#449]
After Warm-reboot, I see a SET request on the ACL Entry with the SAI_ACL_ENTRY_ATTR_ACTION_COUNTER attribute.
However, the corresponding ACL counter RID being passed in this request from syncd is incorrect.
 
This ACL counter RID received in the request is random. This counter RID belongs to another ACL Entry.
I have not observed “new” RIDs. I have only seen a counter rid that is linked to another entry.
 
I had tested another case where I configured only 1 ACL Entry. In this case, warm-reboot was proceeding without any issue most of the time.
But, since we also have a default ACL entry (Drop all) created in this scenario, we receive its Counter RID sometimes and crash.

**Comment by kcudnik** [comment]
this is related to the fact that those counters/objects are indistingusahble from syncd perspective, object comparsion after warm boot is done using object attributes, and not actual function where counters is assigned

what crash are you talking about ?

**Comment by anirudhnr** [comment]
Yes, the counters are indistinguishable from the sync perspective. This is causing the ACL entries to be bound to the wrong counter or two ACL entries are being bound to the same counter. I meant to say that the orchagent process crashes because the SDK returns an error when there is a GET/DELETE request on these ACL entries.

**Comment by kcudnik** [comment]
Can you give any specific scenario? like when acl entries and counters are created and at which point when called delete it causes to crash ? maybe sairedis recording ?

**Comment by anirudhnr** [comment]
Kamil,
I've attached SAIREDIS, SWSS and SAI SDK logs after warm reboot. From what I've observed here, there is a SET call happening after warmboot on an ACL Entry with a wrong ACL Counter which causes the SDK to return an error and the orchagent crashes. I wasn't able to replicate the Delete scenario today, since there is a failure seen right after warmboot.


[logs.txt](https://github.com/Azure/sonic-sairedis/files/3249932/logs.txt)

**Comment by kcudnik** [comment]
this is great, can you also attach /var/log/swss/sairedis.rec from that session?

**Comment by stcheng** [comment]
according to the discussion, after warm reboot, the counters/rules relationship is broken and there is currently no way of rebuilding this correlation?

**Comment by kcudnik** [comment]
yes seems like it

**Comment by anirudhnr** [comment]
I've emailed the logs to you. Please check and let me know if you need anything else.

**Comment by kcudnik** [comment]
Really sorry for the delay, i was very busy, here is fix: https://github.com/Azure/sonic-sairedis/pull/484

**Comment by kcudnik** [comment]
fixed
