### ISSUE TITLE
How is orchagent connecting to ASIC_DB?

### ISSUE THREAD

**Issue by vinayam66** [Azure/sonic-sairedis#466]
How is orchagent connecting to ASIC_DB? Ochagent is connecting to APPL_DB using DBConnector. What is orchagent using to communicate with ASIC_DB? Where is the code located for this connection?

**Comment by stcheng** [comment]
close the duplicate question

**Comment by wendani** [comment]
search g_asicState 
https://github.com/Azure/sonic-sairedis/issues/466#issue-453779893

**Comment by vinayam66** [comment]
> search g_asicState

Hi Wenda Ni,
g_asicState is a table of ASIC_DB. My question is how does Orchagent communicate with ASIC_DB?

**Comment by wendani** [comment]
There is ConsumerTable in the syncd that listens to the field value tuples set to the table. This is how the communication is done.

**Comment by bandaru-viswanath** [comment]
> > search g_asicState
> 
> Hi Wenda Ni,
> g_asicState is a table of ASIC_DB. My question is how does Orchagent communicate with ASIC_DB?

Did you look at the sai-redis api that orchagent uses ?

**Comment by vinayam66** [comment]
> There is ConsumerTable in the syncd that listens to the field value tuples set to the table. This is how the communication is done.

Correct me if I'm wrong, but I think you are talking about communication between syncd and ASIC_DB. 
We want to add a new feature to SONiC. Orchagent is supposed to take data from APPL_DB, process it and store the processed data in ASIC_DB. I am just wondering how Orchagent is communicating with ASIC_DB? To communicate with APPL_DB it is using DBConnector. I don't see similar thing happening with ASIC_DB?
How does Orchagent store data in ASIC_DB?

**Comment by bandaru-viswanath** [comment]
Did you look at the sai-redis API ?

**Comment by vinayam66** [comment]
> Did you look at the sai-redis API ?

You mean sai-redis.h in sonic-sairedis github folder?

**Comment by bandaru-viswanath** [comment]
OrchAgent uses sairedis api to talk to ASIC_DB. Look for "sairedis" in the SONiC architecture [guide](https://github.com/Azure/SONiC/wiki/Architecture) for different orchagents, and how they talk to asicdb.
