### ISSUE TITLE
[BRCM SAI] Why set log level of version-information entry as "ERR" in syncd log?

### ISSUE THREAD

**Issue by CharlieChenEC** [Azure/sonic-sairedis#501]
On AS7816-64X which uses Broadcom ASIC, there is a log entry shown below in syncd log which contains version information.

>Nov  4 03:01:47.652728 as7816-64x ERR syncd#syncd: sai_api_initialize:112 BRCM SAI ver: [3.5.2.3], OCP SAI ver: [1.4], SDK ver: [6.5.14]

It seems that log entry is not an error actually.

Why is the log level for that entry being set as "ERR"? Why not set it as "NOTICE" or any lower log level?

**Comment by CharlieChenEC** [comment]
@kcudnik @lguohan Could you please comment on the question?

Thanks in advance.

**Comment by kcudnik** [comment]
hey, this seems like a message from vendor SAI, we dont have control on what error level this message is, we can kindly ask to reduce to notice

**Comment by kcudnik** [comment]
fixed
