### ISSUE TITLE
Errors while installing sonic-sairedis

### ISSUE THREAD

**Issue by vinayam66** [Azure/sonic-sairedis#559]
When I try to install the 'libsairedis, syncd' packages using '**sudo apt-get install libsairedis syncd**', I get the following error :

Reading package lists... Done
Building dependency tree...
Reading state information... Done
E: Unable to locate package libsairedis
E: Unable to locate package syncd

Actually this has been the case for other related packages too like **libswsscommon libswsscommon-dev**
![sairedis0](https://user-images.githubusercontent.com/50358835/73909912-d5c55480-48d3-11ea-8748-82291f6a6159.PNG)

When I try to install using git, I get the following error while running the 'make && sudo make install' command : 

root@sonic-Standard-PC-i440FX-PIIX-1996:/sonic-sairedis# **make && sudo make install**
make  all-recursive
make[1]: Entering directory '/sonic-sairedis'
Making all in meta
make[2]: Entering directory '/sonic-sairedis/meta'
Makefile:609: ../SAI/meta/.deps/libsaimeta_la-saimetadata.Plo: No such file or directory
Makefile:610: ../SAI/meta/.deps/libsaimeta_la-saimetadatautils.Plo: No such file or directory
Makefile:611: ../SAI/meta/.deps/libsaimeta_la-saiserialize.Plo: No such file or directory
make[2]: *** No rule to make target '../SAI/meta/.deps/libsaimeta_la-saiserialize.Plo'.  Stop.
make[2]: Leaving directory '/sonic-sairedis/meta'
Makefile:404: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/sonic-sairedis'
Makefile:336: recipe for target 'all' failed
make: *** [all] Error 2

![sairedis](https://user-images.githubusercontent.com/50358835/73908635-56825180-48d0-11ea-8b5b-acf141b1110a.PNG)

How to fix this error? 

Regards,
Vinay

**Comment by abanu-ms** [comment]
I'm getting the same error, and the only way until now I found to get past that error is to run git clean -xfd and start over again. Isn't there a better way?

**Comment by kcudnik** [comment]
if you want to build from source, you need SAI directory, if you clone from git do this:
```git submodule update --init --recursive ```

**Comment by kcudnik** [comment]
And there is already similar question: https://github.com/Azure/sonic-sairedis/issues/697

**Comment by kcudnik** [comment]
is this problem still stands?

**Comment by kcudnik** [comment]
closing, please reopen if error still exists
