### ISSUE TITLE
syncd failed to restart when the database is not empty

### ISSUE THREAD

**Issue by stcheng** [Azure/sonic-sairedis#56]
ERR syncd: :- processSingleVid: failed to find VID 6300000000000600 in OIDs map

**Comment by kcudnik** [comment]
This is router interface object id, let me take a look

**Comment by kcudnik** [comment]
you are creating in this order:
- router interface
- route pith that RI object ID
- neihgbor entry with RI object ID
- next-hop with that RI object ID

then you remove router interface (also from db)
then syncd restarts, and route/neighbor/next hop is still pointing to 
that object id in attributes

you need to remove route/neighbor/next-hop before removing router interface

i actually dont know what SAI standard says about this

i also found that when you remove neighbor entry:
internal_redis_generic_remove: generic remove key: 23000000:0000000000000000000000000a000001
route interface object id in this case is all zeros, so not pointing to valid object id 
lets figure this out offline

and also im curious how this works on the first place when we restart syncd do interface up, wait and then start syncd again and it works fine, no clue why thsi works, and when restarting when not all interfaces removed, then it fails, some hardware timing issues ?

**Comment by kcudnik** [comment]
I think this is solved.
