### ISSUE TITLE
redisPutFdbEntryToAsicView: event type SAI_FDB_EVENT_MOVE not supported

### ISSUE THREAD

**Issue by SavchukRomanLv** [Azure/sonic-sairedis#579]
Error message in /var/log/syslog appears when executing dhcp_relay test case.
**Steps to reproduce:** 
Run dhcp_relay test case: 
ansible-playbook test_sonic.yml -i {INVENTORY} --limit {DUT_NAME} -e testcase_name=dhcp_relay -e testbed_name={TESTBED_NAME}
**Actual result:** test fails due to error message 
ERR syncd[27]: :- redisPutFdbEntryToAsicView: event type SAI_FDB_EVENT_MOVE not supported, FIXME\\n'
**Expected result:** test passed 

**Show version:** 
SONiC Software Version: SONiC.HEAD.600-dirty-20200318.091958
Distribution: Debian 9.12
Kernel: 4.9.0-11-2-amd64
Platform: x86_64-arista_7170_64c
HwSKU: Arista-7170-64C

**Comment by kcudnik** [comment]
supported
