### ISSUE TITLE
saidump takes too much time to execute when we try to dump 40K routes

### ISSUE THREAD

**Issue by tomer-israel** [Azure/sonic-sairedis#918]
on saidump.cpp line 427 ([https://github.com/Azure/sonic-sairedis/blob/master/saidump/saidump.cpp#L427](https://github.com/Azure/sonic-sairedis/blob/master/saidump/saidump.cpp#L427) )
we try to dump all the ASIC_DB content using Table::dump() function ([https://github.com/Azure/sonic-swss-common/blob/master/common/table.cpp#L187](https://github.com/Azure/sonic-swss-common/blob/master/common/table.cpp#L187))

this function is calling a redis to run a lua script [table_dump.lua](https://github.com/Azure/sonic-swss-common/blob/master/common/table_dump.lua) which retrieves all the data from ASIC_DB.
The execution time for this lua script is between 6 to 12 seconds when we have more than 40K vnet routes.

The long execution time can cause errors:
```
DEBUG syncd#saidump: :> main: enter
ERR syncd#SDK: :- checkReplyType: Expected to get redis type 5 got t
ype 6, err: BUSY Redis is busy running a script. You can only call SCRIPT KILL or SHUTDOWN NOSAVE.
INFO syncd#supervisord: syncd init_buffer_resource_limits[
INFO syncd#supervisord: syncd num_ingress_pools:8
INFO syncd#supervisord: syncd num_egress_pools:8
INFO syncd#supervisord: syncd num_shared_headroom_pools:1
INFO syncd#supervisord: syncd num_total_pools:42
INFO syncd#supervisord: syncd num_port_queue_buff:16
INFO syncd#supervisord: syncd num_port_pg_buff:8
INFO syncd#supervisord: syncd num_headroom_port_buff:9
INFO syncd#supervisord: syncd unit_size:96
INFO syncd#supervisord: syncd max_buffers_per_port:94
INFO syncd#supervisord: syncd init_buffer_resource_limits]
INFO syncd#supervisord: syncd mlnx_init_buffer_pool_ids[
INFO syncd#supervisord: syncd default_ingress_pool_id:0
INFO syncd#supervisord: syncd management_ingress_pool_id:2
INFO syncd#supervisord: syncd base_ingress_user_sx_pool_id:4
INFO syncd#supervisord: syncd default_egress_pool_id:12
INFO syncd#supervisord: syncd management_egress_pool_id:14
INFO syncd#supervisord: syncd base_egress_user_sx_pool_id:16
INFO syncd#supervisord: syncd default_multicast_pool_id:10
INFO syncd#supervisord: syncd user_pool_step:2
INFO syncd#supervisord: syncd mlnx_init_buffer_pool_ids]
INFO syncd#supervisord: syncd terminate called without an active exception
INFO pmon#supervisord 2021-08-25 14:54:28,424 INFO exited: psud (terminated by SIGABRT (core dumped); not expected)
INFO syncd#supervisord 2021-08-25 14:54:30,675 INFO exited: syncd (terminated by SIGABRT (core dumped); not expected)
NOTICE syncd#saidump: :- dump: getting took 8.642243 sec
```
on the above example, the execution time of the saidump took more than 8 seconds and it caused the syncd to be terminate (SIGTERM)

we don't see the termination of syncd all the times that we run saidump.
usually when the execution time of saidump is more than 8 seconds we see this syncd termination

**Comment by kcudnik** [comment]
should this be issue in sonic-swss-common ?

**Comment by kcudnik** [comment]
also are those ipv6 routes ?

**Comment by kcudnik** [comment]
This is related to this: https://github.com/Azure/sonic-buildimage/issues/3008 and this https://github.com/redis/redis/issues/8077

**Comment by kcudnik** [comment]
To temporary mitigate this we could change lua-time-limit in /etc/redis/redis.conf which is default 5seconds, then other redis APIS will start giving response BUSY

**Comment by tomer-israel** [comment]
> This is related to this: [Azure/sonic-buildimage#3008](https://github.com/Azure/sonic-buildimage/issues/3008) and this [redis/redis#8077](https://github.com/redis/redis/issues/8077)

it's the same issue, so I will close this one
thanks

**Comment by kcudnik** [comment]
Unfortunately LUA in redis will not be updated since it has some backward comparability problems with new versions, but i asked for a fix in current repo and made PR here: https://github.com/redis/redis/pull/9449
